### ISSUE TITLE
Simplify matrix usage

### ISSUE THREAD

**Issue by djhoese** [epassaro/cache-conda-envs#3]
Thanks for the examples and blog post about this. I had trouble working with your example because you defined each matrix environment separately so you could define a label and prefix. However, I usually use lists for my matrix entries like:

```yaml
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10"]
```

which means I can't easily define prefix/label (as far as I know). I cam up with an alternative that doesn't require the user to know what platform they are on by updating the DATE job:

```yaml
      - name: Set cache environment variables
        shell: bash -l {0}
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          CONDA_PREFIX=$(python -c "import sys; print(sys.prefix)")
          echo "CONDA_PREFIX=$CONDA_PREFIX" >> $GITHUB_ENV
```

I also updated my cache entry to include the python version:

```yaml
      - uses: actions/cache@v3
        with:
          path: ${{ env.CONDA_PREFIX }}
          key: ${{ matrix.os }}-${{matrix.python-version}}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache
```
